name: build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install gcc-multilib

      - name: Add targets
        run: |
          rustup target add x86_64-unknown-linux-gnu
          rustup target add i686-unknown-linux-gnu

      - name: Update dependencies
        run: cargo update -p ntapi

      - name: Build 64-bit
        run: cargo build --verbose --target x86_64-unknown-linux-gnu --release

      - name: Build 32-bit
        run: cargo build --verbose --target i686-unknown-linux-gnu --release

      - name: Strip 64-bit
        run: strip target/x86_64-unknown-linux-gnu/release/gluapack

      - name: Strip 32-bit
        run: strip target/i686-unknown-linux-gnu/release/gluapack

      - name: Rename binaries
        run: |
          mv target/x86_64-unknown-linux-gnu/release/gluapack target/x86_64-unknown-linux-gnu/release/gluapack_linux64
          mv target/i686-unknown-linux-gnu/release/gluapack target/i686-unknown-linux-gnu/release/gluapack_linux32

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/gluapack_linux64
            target/i686-unknown-linux-gnu/release/gluapack_linux32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add targets
        run: |
          rustup target add x86_64-pc-windows-msvc
          rustup target add i686-pc-windows-msvc

      - name: Update dependencies
        run: cargo update -p ntapi

      - name: Build 64-bit
        run: cargo build --verbose --target x86_64-pc-windows-msvc --release

      - name: Build 32-bit
        run: cargo build --verbose --target i686-pc-windows-msvc --release

      - name: Rename binaries
        run: |
          ren target\x86_64-pc-windows-msvc\release\gluapack.exe gluapack_win64.exe
          ren target\i686-pc-windows-msvc\release\gluapack.exe gluapack_win32.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target\x86_64-pc-windows-msvc\release\gluapack_win64.exe
            target\i686-pc-windows-msvc\release\gluapack_win32.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
